# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/PMS.Backend.Common"
    schedule:
      interval: "weekly"
    assignees:
      - "jorgeparavicini"
    target-branch: "dev"
      
  - package-ecosystem: "nuget"
    directory: "/PMS.Backend.Core"
    schedule:
      interval: "weekly"
    assignees:
      - "jorgeparavicini"
    target-branch: "dev"
      
  - package-ecosystem: "nuget"
    directory: "/PMS.Backend.Features"
    schedule:
      interval: "weekly"
    assignees:
      - "jorgeparavicini"
    target-branch: "dev"
      
  - package-ecosystem: "nuget"
    directory: "/PMS.Backend.Service"
    schedule:
      interval: "weekly"
    assignees:
      - "jorgeparavicini"
    target-branch: "dev"
      
  - package-ecosystem: "nuget"
    directory: "/PMS.Backend.Test"
    schedule:
      interval: "weekly"
    assignees:
      - "jorgeparavicini"
    target-branch: "dev"
