version: '3.4'

services:
  pms.backend.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  pms.db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "PMS_PASSWORD"
      POSTGRES_USER: "PMS_USER"
      POSTGRES_DB: "PMS"
      
      
