version: '3.4'

services:
  pms.backend.service:
    image: ${DOCKER_REGISTRY-}pmsbackendservice
    build:
      context: .
      dockerfile: PMS.Backend.Service/Dockerfile
    depends_on:
      - pms.db

  pms.db:
    image: "mcr.microsoft.com/mssql/server"
