name: Run Tests and Generate Codecov Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Setup NuGet package cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore PMS.Backend.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release PMS.Backend.sln

      - name: Test
        run: dotnet test PMS.Backend.sln --no-build --configuration Release --collect:"XPlat Code Coverage" -- RunSettings.DisableAppDomain=true --settings coverage.runsettings

      - name: Install ReportGenerator
        run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path ./tools

      - name: Generate coverage report
        run: |
          ./tools/reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:"Cobertura;HtmlInline_AzurePipelines;Badges"
          ls -R coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/Cobertura.xml
          fail_ci_if_error: true
